### PR TITLE
ethereum websocket

### PR DESCRIPTION
**Pull request by florianlenz**
- added websocket ethereum interface for VM
- changed function validator

### CODE REVIEW

**Comment by florianlenz** [comment]
@borjantrajanoski 
I added simplification of the websocket connect retry. I also changed the ID generation. But instead of incrementing an counter I switched to the unix timestamp in nano seconds. 

```go
fmt.Println(time.Now().UnixNano())
fmt.Println(time.Now().UnixNano())
```

outputs: 

```
1529870162028575612
1529870162028601124
```

I think those values are good for this use case. As you can see the last 6 digits are different.

**Comment by borjantrajanoski** [comment]
The current implementation is functional and UnixNano seems to be a better solution than an incrementing counter 👍

As a side note, when UnixNano() is called concurrently, although it's rare, there are still collisions so it's not a fully reliable unique ID generation mechanism just on it's own.

```
for {
	id := time.Now().UnixNano()
		if _, exist := ws.requests[id]; !exist { // This check is still important
			r.ID = id
			ws.requests[id] = c
			break
		}
}
```
```
package main

import (
	"fmt"
	"sync"
	"time"
)

func main() {
	start := make(chan struct{})
	var wg sync.WaitGroup
	for i := 0; i < 100000; i++ {
		wg.Add(1)
		go func() {
			t := time.Now().UnixNano()
			<-start
			defer wg.Done()
			fmt.Println(t)
		}()
	}
	close(start)
	wg.Wait()
}

```
> Duplicate line numbers : 
> ( 14788 dupe of 14775 ): 1529927429502470480
> ( 22765 dupe of 22756 ): 1529927429484943341
> ( 41421 dupe of 41411 ): 1529927429452284962
> ( 93618 dupe of 93312 ): 1529927429347448974
> ( 98066 dupe of 98063 ): 1529927429380044425
> ( 99619 dupe of 99600 ): 1529927429376066630

[concurrentUnixNano100k.txt](https://github.com/Bit-Nation/panthalassa/files/2133000/concurrentUnixNano100k.txt)

**Review by borjantrajanoski — APPROVED** [review]
Looks good 👍

**Comment by florianlenz** [comment]
Thanks. Make sense regarding the go routines. That the reason why I am still checking if the id is taken (just to be sure).

**Pull request merged**
